RESPONSES = [
	"Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
	"Maecenas vel nulla consectetur, elementum neque commodo, fringilla diam.",
	"Aenean id metus condimentum, egestas elit a, volutpat urna.",
	"Ut commodo quam vel sapien commodo, ac consequat orci semper.",
	"Phasellus euismod dui at lorem facilisis, ut accumsan ante tincidunt.",
	"Fusce consequat odio eget fermentum consequat.",
	"Nam faucibus risus tempus, condimentum orci condimentum, sagittis lectus.",
	"Nullam vestibulum justo luctus arcu dignissim, ut vulputate enim congue.",
	"Nulla a ipsum sit amet risus aliquet aliquet vel at quam.",
	"In cursus dui et rutrum consectetur.",
	"Donec ornare augue vel tortor ultrices suscipit.",
	"Vestibulum fermentum ipsum vitae orci interdum, pharetra tempus metus placerat.",
	"Nunc commodo ipsum eu nunc condimentum, eu vulputate ipsum sollicitudin.",
	"Ut dignissim turpis et libero sollicitudin rutrum.",
	"Maecenas laoreet lectus ut egestas cursus.",
	"Nulla dictum ligula id eros faucibus convallis.",
	"Vivamus quis orci sed justo tincidunt porttitor.",
	"Morbi et felis vel tellus mollis varius.",
	"Vestibulum quis odio vehicula sem volutpat pharetra.",
]
